version: '3.4'

services:
  chatapp:
    image: ${DOCKER_REGISTRY-}chatapp
    build:
      context: .
      dockerfile: ChatApp/Dockerfile
    environment:
      - MONGODB_CN
    restart: always
    networks:
     - signalr-app-network
    depends_on:
      - mongo
      - sqldb
      

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ":/data/db"
    restart: always
    networks:
      - signalr-app-network


  sqldb:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      SA_PASSWORD: "${DB_PW}"
      ACCEPT_EULA: "Y"
    ports:
      - "1402:1433"
    restart: always
    networks:
     - signalr-app-network


networks:
  signalr-app-network:
    driver: bridge