version: '3.4'

services:
  chatapp:
    image: ${DOCKER_REGISTRY-}chatapp
    build:
      context: .
      dockerfile: ChatApp/Dockerfile
    environment:
      - MONGODB_CN
    restart: always
    networks:
     - signalr-app-network
    depends_on:
      - mongo
      - sqldb
      

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27016:27017"
    volumes:
      - "mongovol:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - webapplication1-network


  sqldb:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      SA_PASSWORD: "${DB_PW}"
      ACCEPT_EULA: "Y"
    ports:
      - "1402:1433"
    restart: always
    networks:
     - signalr-app-network


networks:
  signalr-app-network:
    driver: bridge

volumes:
  mongovol: